apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobqueue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobqueue-app
  template:
    metadata:
      labels:
        app: jobqueue-app
    spec:
      containers:
      - name: app
        image: jobqueue-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/jobjet"
---
apiVersion: v1
kind: Service
metadata:
  name: jobqueue-app
spec:
  selector:
    app: jobqueue-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
